# Generated by Django 4.2.3 on 2025-04-17 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyexpenses', '0003_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense',
            field=models.PositiveIntegerField(),
        ),
    ]
