# Generated by Django 4.2.3 on 2025-04-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthlyexpenses', '0004_expenses_date_alter_expenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthlyexpenses.source'),
        ),
    ]
